apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bookstore-front-end.name" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "bookstore-front-end.name" . }}-proxy
    chart: {{ template "bookstore-front-end.chart" . }}-proxy
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bookstore-front-end.name" . }}-proxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bookstore-front-end.name" . }}-proxy
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "bookstore-front-end.serviceAccountName" . }}
      volumes:
      - name: {{ template "bookstore-front-end.name" . }}-proxy-config
        configMap:
          name: {{ template "bookstore-front-end.name" . }}-proxy-config
      containers:
        - name: {{ .Chart.Name }}-proxy
          image: "nginx"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ template "bookstore-front-end.name" . }}-proxy-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            httpGet:
              path: /
              port: http
